### ISSUE TITLE
terratest made private?

### ISSUE THREAD

**Issue by sarkis** [gruntwork-io/toc#5]
I was writing some tests for a PR to `terraform-aws-consul` module - and had some issues when installing dependencies via glide before running them. The error I am getting:

```
[WARN]	Unable to checkout github.com/gruntwork-io/terratest
[ERROR]	Update failed for github.com/gruntwork-io/terratest: Unable to get repository: Cloning into '/home/sarkis/.glide/cache/src/git-github.com-gruntwork-io-terratest'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128
[ERROR]	Failed to install: Unable to get repository: Cloning into '/home/sarkis/.glide/cache/src/git-github.com-gruntwork-io-terratest'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128
```

Looks like this repository is 404-ing which means it was likely either renamed, deleted, or possibly made private? I'm guessing it was made private for one reason or another :) but wanted to confirm before trying to proceed a different way.

**Comment by brikis98** [comment]
Terratest has always been private. We've wanted to open source it for ages, but haven't had time to yet :( 

Fortunately, it's on our roadmap for the next few months!

**Comment by sarkis** [comment]
Nice - thanks for the quick respone @brikis98! Closing this for now.. will find a way around testing :)
