### ISSUE TITLE
Most of the links in the TOC are not found

### ISSUE THREAD

**Issue by whytoe** [gruntwork-io/toc#6]

**Comment by brikis98** [comment]
Right at the top of the page:

> This repo is a convenient way to find all of the repositories created and maintained by Gruntwork. It is intended primarily for Gruntwork's customers.

> Please note that most of the links are private. If you don't have access to them, you'll get a 404 page! To gain access, you must be a Gruntwork customer. See gruntwork.io for more info and feel free to reach out to us at info@gruntwork.io if you have questions.
